class UserNotFound(Exception):
    pass


class AuthFailed(Exception):
    pass
